spring.application.name=demo-service

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=jdbc:postgresql://localhost:5432/book-db
spring.datasource.username=root
spring.datasource.password=root

# Show and format SQL queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DDL mode (create, create-drop, validate, update, none)
# 'update' create or update tables on the basis of the @Entity classes.
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
