spring.application.name=demo-service
spring.datasource.url=jdbc:postgresql://db:5432/bookdb
spring.datasource.password=Its2025!
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


